import AlbumPage from "@/components/album/AlbumPage";
import React from "react";
import action from "@/public/images/action.jpg";

export const metadata = {
  title: "Action | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/action",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const Drink = () => {
  return (
    <React.Fragment>
      <AlbumPage
        list="Action"
        color="bg-gray-500"
        quote="In this moment, I am safe"
        author="-Rick Hanson"
        image={action}
      />
    </React.Fragment>
  );
};

export default Drink;
