import ContactPage from "@/components/contact";
import Animation from "@/layout/animation";
import React from "react";
import { useTranslations } from "next-intl";

export const metadata = {
  title: "Contact | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/Contact",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const Contact = () => {
  const t = useTranslations("contact");
  const translateObj = {
    intro: t("intro"),
    name: t("name"),
    email: t("email"),
    subject: t("subject"),
    message: t("message"),
    submit: t("submit"),
  };
  return (
    <Animation>
      <ContactPage translateObj={translateObj} />
    </Animation>
  );
};

export default Contact;
