import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Header from "@/layout/header";
import "../../styles/globals.css";

export const metadata = {
  title: "Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

interface Layout {
  children: React.ReactNode;
  params: { locale: string };
}

const LocaleLayout: React.FC<Layout> = ({ children, params }) => {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className="bg-white p-16 md:p-24 lg:p-32 xl:p-40 gap-16 md:gap-24 lg:gap-32 xl:gap-40 flex flex-col xl:flex-row min-h-screen overflow-y-auto overflow-x-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
};

export default LocaleLayout;
