import AboutPage from "@/components/about";
import Animation from "@/layout/animation";
import React from "react";

export const metadata = {
  title: "About | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/About",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const About = () => {
  return (
    <Animation>
      <AboutPage />
    </Animation>
  );
};

export default About;
