import AlbumPage from "@/components/album/AlbumPage";
import React from "react";
import food from "@/public/images/food.jpg";

export const metadata = {
  title: "Food | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/food",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const Food = () => {
  return (
    <React.Fragment>
      <AlbumPage list="Food" color="bg-gray-500" quote="There is no love sincerer than the love of food" author="-George Bernand Shaw" image={food} />
    </React.Fragment>
  );
};

export default Food;
