import AlbumPage from "@/components/album/AlbumPage";
import React from "react";
import lifestyle from "@/public/images/lifestyle.jpg";

export const metadata = {
  title: "Lifestyle | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/lifestyle",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const Lifestyle = () => {
  return (
    <React.Fragment>
      <AlbumPage
        list="Lifestyle"
        color="bg-gray-500"
        quote="Don't take a photograph, Make it"
        author="-Ansel Adam"
        image={lifestyle}
      />
    </React.Fragment>
  );
};

export default Lifestyle;
