import PostPage from "@/components/post/PostPage";
import React from "react";

export const metadata = {
  title: "Blogs | Tran Food Photography",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://tranfood-photo.vercel.app/Blogs",
    languages: {
      en: "https://tranfood-photo.vercel.app/en",
      vi: "https://tranfood-photo.vercel.app/vi",
    },
  },
};

const Recipes = () => {
  return <PostPage list="Blogs"/>;
};

export default Recipes;
